fixed the module.exports error
after the error: color is not a function, see issue #1 
changed default export to module.exports and tried locally, and it worked.
for a complete solution, you need to change the readme file too.